- name: Instances creation for expense project
  hosts: local
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    instances: [ "database", "backend", "frontend", "lb" ]
    route53_zone_name: trivikram.online
    operation: create
  tasks:
  - name: Create 4 instances for expense project
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ ami_id }}"
      instance_type: t3.micro
      security_groups: 
      - "{{ item }}"
      - common
    loop: "{{ instances }}"
    register: ec2_output
    when: operation == "create"

  - name: Save instance details
    copy:
      content: "{{ item.instances | to_nice_yaml }}"
      dest: "/tmp/{{ item.item }}.log"
    loop: "{{ ec2_output.results }}"
    ignore_errors: true
    when: operation == "create"


  - name: Create R53 records for database, backend, frontend and lb with private ip in expense project
    amazon.aws.route53:
      state: present
      zone: "{{ route53_zone_name }}"
      record: "{{ item.item }}.{{ route53_zone_name }}"
      type: A
      value: "{{ item.instances[0].private_ip_address }}"
      ttl: 1
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: 
    - operation == "create"
    - instances != "lb"

  - name : Overwrite R53 records for lb with public ip in expense project
    amazon.aws.route53:
      state: present
      zone: "{{ route53_zone_name }}"
      record: "{{ route53_zone_name }}"
      type: A
      value: "{{ item.instances[0].public_ip_address }}"
      ttl: 1
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "lb"
    - operation == "create"

  - name: Get EC2 info
    amazon.aws.ec2_instance_info:
    filters:
      tag:Name: "{{ item }}"
      instance-state-name: running
    loop: "{{ instances }}"
    register: ec2_info
    when: operation == "delete"

  - name: Delete R53 records for database, backend, frontend and lb with private ip in expense project
    amazon.aws.route53:
      state: absent
      zone: "{{ route53_zone_name }}"
      record: "{{ item.item }}.{{ route53_zone_name }}"
      type: A
      value: "{{ item.instances[0].private_ip_address }}"
      ttl: 1
      overwrite: true
    loop: "{{ ec2_info.results }}"
    when: 
    - operation == "delete"
    - instances != "lb"

  - name: Delete R53 records for lb with overwritten public ip in expense project
    amazon.aws.route53:
      state: absent
      zone: "{{ route53_zone_name }}"
      record: "{{ route53_zone_name }}"
      type: A
      value: "{{ item.instances[0].public_ip_address }}"
      ttl: 1
      overwrite: true
    loop: "{{ ec2_info.results }}"
    when: 
    - item.item == "lb"
    - operation == "delete"

  - name: Delete EC2 instances for expense project
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}"
      wait: false
    loop: "{{ instances }}"
    when: operation == "delete"