- name: Configuring the Frontend
  hosts: frontend
  become: yes

  tasks:
  - name: Change hostname to frontend
    hostname:
      name: frontend.trivikram.online

  - name: Install nginx
    package:
      name: nginx
      state: present
      
  - name: Start and enable nginx
    service:
      name: nginx
      state: started
      enabled: yes

  
  - name: Delete the Entire html directory
    file:
      path: /usr/share/nginx/html/
      state: absent

  - name: Delete frontend.zip in tmp directory
    file:
      path: /tmp/frontend.zip
      state: absent

  - name: Create the HTML directory
    file: 
      path: /usr/share/nginx/html/
      state: directory

  - name: Download frontend code file
    get_url:
      url: https://raw.githubusercontent.com/daws-90s/expense-documentation/refs/heads/main/artifacts/expense-frontend-v3.tar.gz
      dest: /tmp/frontend.zip
  
  - name: Unzip the .zip file
    unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: Create the expense.conf file
    template:
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf

  - name: Test the nginx configuration
    command: nginx -t
    register: nginx_output
    ignore_errors: true

  - name: Print the nginx configuration output
    debug:
      msg: "{{ nginx_output.stdout }}"

  - name: Start and Enable nginx
    service:
      name: nginx
      state: restarted
      enabled: yes